### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Meulator** [bigb0sss/gogophish#2]
Hello, do you think you can update the script for it to work with latest version? Got a bunch of errors while installing : 

`./gogophish_v2.0.sh: line 149: fuser: command not found
[*] Downloading gophish (x64)...
# golang.org/x/sys/unix
/root/go/src/golang.org/x/sys/unix/syscall.go:83:16: undefined: unsafe.Slice
/root/go/src/golang.org/x/sys/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
/root/go/src/golang.org/x/sys/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
# github.com/emersion/go-message
/root/go/src/github.com/emersion/go-message/charset.go:24:9: undefined: errors.As
/root/go/src/github.com/emersion/go-message/encoding.go:27:9: undefined: errors.As
# github.com/go-sql-driver/mysql
/root/go/src/github.com/go-sql-driver/mysql/nulltime.go:36:15: undefined: sql.NullTime
# github.com/mattn/go-sqlite3
/root/go/src/github.com/mattn/go-sqlite3/sqlite3_type.go:75:25: undefined: sql.NullTime
[+] Gophish Started: https://:3333 - [Login] Username: admin, Temporary Password:
./gogophish_v2.0.sh: line 249: fuser: command not found
`

Thanks!

**Comment by Meulator** [comment]
Tried Ubuntu 20.1, 20.0, Debian 10

**Comment by bigb0sss** [comment]
Hi @Meulator Thanks for reporting the issue. I will take a look and try to update it in near future. Also, feel free to make a pull request if you want. Thanks again.

**Comment by mplattner** [comment]
I've fixed the issue in my own fork in https://github.com/mplattner/gogophish/commit/94c0fd85f2c73802c4b647eb20f4f20e836e01a4 and https://github.com/mplattner/gogophish/commit/bc4c0e98c749ae8398eb64d026f53b2da9b92fd9.
I only fixed it for `setupEmail()`, but not `setupSMS()`, that's why I didn't create a PR, but feel free to use my changes in your repo.

**Comment by Meulator** [comment]
> I've fixed the issue in my own fork in [mplattner@94c0fd8](https://github.com/mplattner/gogophish/commit/94c0fd85f2c73802c4b647eb20f4f20e836e01a4) and [mplattner@bc4c0e9](https://github.com/mplattner/gogophish/commit/bc4c0e98c749ae8398eb64d026f53b2da9b92fd9). I only fixed it for `setupEmail()`, but not `setupSMS()`, that's why I didn't create a PR, but feel free to use my changes in your repo.

Hello,

thanks a lot ; i tried, using git clone and replacing with your username, all seems fine, but : 

I got a warning : 

`[+] Unzip already installed
[+] Golang already installed
[+] Git already installed
[*] Installing pip...
[+] Gcc already installed
[*] Installing libc-dev...
mkdir: cannot create directory ‘/go’: File exists
mkdir: cannot create directory ‘/go-cache’: File exists
[*] Downloading gophish (x64)...
[*] Creating a gophish folder: /opt/gophish
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
[*] Creating a gophish log folder: /var/log/gophish
`

And then, gogophish should display ip adresss, username and password, but it does not.

When i relaunch gogophish with -d domainname.xx i get :  


`[+] Check if the cert is correctly installed: https://xxx.io/robots.txt
Job for gophish.service failed because of unavailable resources or another system error.
See "systemctl status gophish.service" and "journalctl -xeu gophish.service" for details.
cat: /var/log/gophish/gophish.error: No such file or directory
[+] Gophish Started: https://:3333 - [Login] Username: admin, Temporary Password:
`


Checking the logs gives me : gophish.service: Failed to load environment files: No such file or directory

Service is enable but wont start

Thanks

**Comment by mplattner** [comment]
```
mkdir: cannot create directory ‘/go’: File exists
mkdir: cannot create directory ‘/go-cache’: File exists
```
I guess that is because you ran the script twice on the same machine?

The sqlite output is just a warning, the created gophish binary still works for me.

In case my change from initd to systemd causes problems for you, you can try to revert my commit https://github.com/mplattner/gogophish/commit/d2d6b6581ec35115aaf955f159c24ab8595a463b.

Sorry I don't have more time to look into this in more detail.

**Comment by bigb0sss** [comment]
I know it's been a while but I have updated the script to properly install the Gophish from the source. There has been some update on Golang-side it looks like. So I just went to easier route to install it from the source directly and you can still update the 'rid' if needed. Yea as @mplattner mentioned that sqlite output is just a warning and it shouldn't prevent you from installing Gophish. Please let me know if there is anything I can update or feel free to make a PR. Thanks!
